// Code generated by ogen, DO NOT EDIT.

package server

import (
	"fmt"
	"time"

	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

func (s *ServerErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

type CreateStbUserBadRequest ErrorMessage

func (*CreateStbUserBadRequest) createStbUserRes() {}

type CreateStbUserInternalServerError ErrorMessage

func (*CreateStbUserInternalServerError) createStbUserRes() {}

type CreateStbUserUnauthorized ErrorMessage

func (*CreateStbUserUnauthorized) createStbUserRes() {}

type CreateTimeEntryBadRequest ErrorMessage

func (*CreateTimeEntryBadRequest) createTimeEntryRes() {}

type CreateTimeEntryInternalServerError ErrorMessage

func (*CreateTimeEntryInternalServerError) createTimeEntryRes() {}

// The payload for creating a time entry.
// Ref: #/CreateTimeEntryRequestBody
type CreateTimeEntryRequestBody struct {
	MatterId         int16     `json:"matterId"`
	TrackingEntityId int32     `json:"trackingEntityId"`
	IsGratias        bool      `json:"isGratias"`
	TimeSpent        float64   `json:"timeSpent"`
	HasStatus        int16     `json:"hasStatus"`
	InvoiceComment   OptString `json:"invoiceComment"`
	InternalNote     OptString `json:"internalNote"`
}

// GetMatterId returns the value of MatterId.
func (s *CreateTimeEntryRequestBody) GetMatterId() int16 {
	return s.MatterId
}

// GetTrackingEntityId returns the value of TrackingEntityId.
func (s *CreateTimeEntryRequestBody) GetTrackingEntityId() int32 {
	return s.TrackingEntityId
}

// GetIsGratias returns the value of IsGratias.
func (s *CreateTimeEntryRequestBody) GetIsGratias() bool {
	return s.IsGratias
}

// GetTimeSpent returns the value of TimeSpent.
func (s *CreateTimeEntryRequestBody) GetTimeSpent() float64 {
	return s.TimeSpent
}

// GetHasStatus returns the value of HasStatus.
func (s *CreateTimeEntryRequestBody) GetHasStatus() int16 {
	return s.HasStatus
}

// GetInvoiceComment returns the value of InvoiceComment.
func (s *CreateTimeEntryRequestBody) GetInvoiceComment() OptString {
	return s.InvoiceComment
}

// GetInternalNote returns the value of InternalNote.
func (s *CreateTimeEntryRequestBody) GetInternalNote() OptString {
	return s.InternalNote
}

// SetMatterId sets the value of MatterId.
func (s *CreateTimeEntryRequestBody) SetMatterId(val int16) {
	s.MatterId = val
}

// SetTrackingEntityId sets the value of TrackingEntityId.
func (s *CreateTimeEntryRequestBody) SetTrackingEntityId(val int32) {
	s.TrackingEntityId = val
}

// SetIsGratias sets the value of IsGratias.
func (s *CreateTimeEntryRequestBody) SetIsGratias(val bool) {
	s.IsGratias = val
}

// SetTimeSpent sets the value of TimeSpent.
func (s *CreateTimeEntryRequestBody) SetTimeSpent(val float64) {
	s.TimeSpent = val
}

// SetHasStatus sets the value of HasStatus.
func (s *CreateTimeEntryRequestBody) SetHasStatus(val int16) {
	s.HasStatus = val
}

// SetInvoiceComment sets the value of InvoiceComment.
func (s *CreateTimeEntryRequestBody) SetInvoiceComment(val OptString) {
	s.InvoiceComment = val
}

// SetInternalNote sets the value of InternalNote.
func (s *CreateTimeEntryRequestBody) SetInternalNote(val OptString) {
	s.InternalNote = val
}

type CreateTimeEntryUnauthorized ErrorMessage

func (*CreateTimeEntryUnauthorized) createTimeEntryRes() {}

type DeleteStbUserByUUIDBadRequest ErrorMessage

func (*DeleteStbUserByUUIDBadRequest) deleteStbUserByUUIDRes() {}

type DeleteStbUserByUUIDInternalServerError ErrorMessage

func (*DeleteStbUserByUUIDInternalServerError) deleteStbUserByUUIDRes() {}

// DeleteStbUserByUUIDNoContent is response for DeleteStbUserByUUID operation.
type DeleteStbUserByUUIDNoContent struct{}

func (*DeleteStbUserByUUIDNoContent) deleteStbUserByUUIDRes() {}

type DeleteStbUserByUUIDNotFound ErrorMessage

func (*DeleteStbUserByUUIDNotFound) deleteStbUserByUUIDRes() {}

type DeleteStbUserByUUIDUnauthorized ErrorMessage

func (*DeleteStbUserByUUIDUnauthorized) deleteStbUserByUUIDRes() {}

// Ref: #/ErrorMessage
type ErrorMessage struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorMessage) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorMessage) SetMessage(val string) {
	s.Message = val
}

type GetStbUserByUUIDBadRequest ErrorMessage

func (*GetStbUserByUUIDBadRequest) getStbUserByUUIDRes() {}

type GetStbUserByUUIDInternalServerError ErrorMessage

func (*GetStbUserByUUIDInternalServerError) getStbUserByUUIDRes() {}

type GetStbUserByUUIDNotFound ErrorMessage

func (*GetStbUserByUUIDNotFound) getStbUserByUUIDRes() {}

type GetStbUserByUUIDUnauthorized ErrorMessage

func (*GetStbUserByUUIDUnauthorized) getStbUserByUUIDRes() {}

type GetStbUsersInternalServerError ErrorMessage

func (*GetStbUsersInternalServerError) getStbUsersRes() {}

type GetStbUsersOKApplicationJSON []StbUser

func (*GetStbUsersOKApplicationJSON) getStbUsersRes() {}

type GetStbUsersUnauthorized ErrorMessage

func (*GetStbUsersUnauthorized) getStbUsersRes() {}

type GetTimeEntriesInternalServerError ErrorMessage

func (*GetTimeEntriesInternalServerError) getTimeEntriesRes() {}

type GetTimeEntriesOKApplicationJSON []TimeEntry

func (*GetTimeEntriesOKApplicationJSON) getTimeEntriesRes() {}

type GetTimeEntriesUnauthorized ErrorMessage

func (*GetTimeEntriesUnauthorized) getTimeEntriesRes() {}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RemoveTimeEntryInternalServerError ErrorMessage

func (*RemoveTimeEntryInternalServerError) removeTimeEntryRes() {}

// RemoveTimeEntryNoContent is response for RemoveTimeEntry operation.
type RemoveTimeEntryNoContent struct{}

func (*RemoveTimeEntryNoContent) removeTimeEntryRes() {}

type RemoveTimeEntryUnauthorized ErrorMessage

func (*RemoveTimeEntryUnauthorized) removeTimeEntryRes() {}

type ServerErrorResponse jx.Raw

// ServerErrorResponseStatusCode wraps ServerErrorResponse with StatusCode.
type ServerErrorResponseStatusCode struct {
	StatusCode int
	Response   ServerErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ServerErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ServerErrorResponseStatusCode) GetResponse() ServerErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ServerErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ServerErrorResponseStatusCode) SetResponse(val ServerErrorResponse) {
	s.Response = val
}

// Ref: #/StbUser
type StbUser struct {
	StbUserId     int32     `json:"stbUserId"`
	StbUserUuid   uuid.UUID `json:"stbUserUuid"`
	StbCustomerId int32     `json:"stbCustomerId"`
	HasStatus     int32     `json:"hasStatus"`
	HasAuthMethod int32     `json:"hasAuthMethod"`
	FirstName     string    `json:"firstName"`
	MiddleName    string    `json:"middleName"`
	LastName      string    `json:"lastName"`
	Initials      string    `json:"initials"`
	DtCreated     time.Time `json:"dtCreated"`
	DtModified    time.Time `json:"dtModified"`
}

// GetStbUserId returns the value of StbUserId.
func (s *StbUser) GetStbUserId() int32 {
	return s.StbUserId
}

// GetStbUserUuid returns the value of StbUserUuid.
func (s *StbUser) GetStbUserUuid() uuid.UUID {
	return s.StbUserUuid
}

// GetStbCustomerId returns the value of StbCustomerId.
func (s *StbUser) GetStbCustomerId() int32 {
	return s.StbCustomerId
}

// GetHasStatus returns the value of HasStatus.
func (s *StbUser) GetHasStatus() int32 {
	return s.HasStatus
}

// GetHasAuthMethod returns the value of HasAuthMethod.
func (s *StbUser) GetHasAuthMethod() int32 {
	return s.HasAuthMethod
}

// GetFirstName returns the value of FirstName.
func (s *StbUser) GetFirstName() string {
	return s.FirstName
}

// GetMiddleName returns the value of MiddleName.
func (s *StbUser) GetMiddleName() string {
	return s.MiddleName
}

// GetLastName returns the value of LastName.
func (s *StbUser) GetLastName() string {
	return s.LastName
}

// GetInitials returns the value of Initials.
func (s *StbUser) GetInitials() string {
	return s.Initials
}

// GetDtCreated returns the value of DtCreated.
func (s *StbUser) GetDtCreated() time.Time {
	return s.DtCreated
}

// GetDtModified returns the value of DtModified.
func (s *StbUser) GetDtModified() time.Time {
	return s.DtModified
}

// SetStbUserId sets the value of StbUserId.
func (s *StbUser) SetStbUserId(val int32) {
	s.StbUserId = val
}

// SetStbUserUuid sets the value of StbUserUuid.
func (s *StbUser) SetStbUserUuid(val uuid.UUID) {
	s.StbUserUuid = val
}

// SetStbCustomerId sets the value of StbCustomerId.
func (s *StbUser) SetStbCustomerId(val int32) {
	s.StbCustomerId = val
}

// SetHasStatus sets the value of HasStatus.
func (s *StbUser) SetHasStatus(val int32) {
	s.HasStatus = val
}

// SetHasAuthMethod sets the value of HasAuthMethod.
func (s *StbUser) SetHasAuthMethod(val int32) {
	s.HasAuthMethod = val
}

// SetFirstName sets the value of FirstName.
func (s *StbUser) SetFirstName(val string) {
	s.FirstName = val
}

// SetMiddleName sets the value of MiddleName.
func (s *StbUser) SetMiddleName(val string) {
	s.MiddleName = val
}

// SetLastName sets the value of LastName.
func (s *StbUser) SetLastName(val string) {
	s.LastName = val
}

// SetInitials sets the value of Initials.
func (s *StbUser) SetInitials(val string) {
	s.Initials = val
}

// SetDtCreated sets the value of DtCreated.
func (s *StbUser) SetDtCreated(val time.Time) {
	s.DtCreated = val
}

// SetDtModified sets the value of DtModified.
func (s *StbUser) SetDtModified(val time.Time) {
	s.DtModified = val
}

func (*StbUser) getStbUserByUUIDRes()    {}
func (*StbUser) updateStbUserByUUIDRes() {}

// Ref: #/StbUserCreateRequestBody
type StbUserCreateRequestBody struct {
	StbUserUuid   uuid.UUID `json:"stbUserUuid"`
	StbCustomerId int32     `json:"stbCustomerId"`
	HasStatus     int32     `json:"hasStatus"`
	HasAuthMethod int32     `json:"hasAuthMethod"`
	FirstName     string    `json:"firstName"`
	MiddleName    string    `json:"middleName"`
	LastName      string    `json:"lastName"`
	Initials      string    `json:"initials"`
}

// GetStbUserUuid returns the value of StbUserUuid.
func (s *StbUserCreateRequestBody) GetStbUserUuid() uuid.UUID {
	return s.StbUserUuid
}

// GetStbCustomerId returns the value of StbCustomerId.
func (s *StbUserCreateRequestBody) GetStbCustomerId() int32 {
	return s.StbCustomerId
}

// GetHasStatus returns the value of HasStatus.
func (s *StbUserCreateRequestBody) GetHasStatus() int32 {
	return s.HasStatus
}

// GetHasAuthMethod returns the value of HasAuthMethod.
func (s *StbUserCreateRequestBody) GetHasAuthMethod() int32 {
	return s.HasAuthMethod
}

// GetFirstName returns the value of FirstName.
func (s *StbUserCreateRequestBody) GetFirstName() string {
	return s.FirstName
}

// GetMiddleName returns the value of MiddleName.
func (s *StbUserCreateRequestBody) GetMiddleName() string {
	return s.MiddleName
}

// GetLastName returns the value of LastName.
func (s *StbUserCreateRequestBody) GetLastName() string {
	return s.LastName
}

// GetInitials returns the value of Initials.
func (s *StbUserCreateRequestBody) GetInitials() string {
	return s.Initials
}

// SetStbUserUuid sets the value of StbUserUuid.
func (s *StbUserCreateRequestBody) SetStbUserUuid(val uuid.UUID) {
	s.StbUserUuid = val
}

// SetStbCustomerId sets the value of StbCustomerId.
func (s *StbUserCreateRequestBody) SetStbCustomerId(val int32) {
	s.StbCustomerId = val
}

// SetHasStatus sets the value of HasStatus.
func (s *StbUserCreateRequestBody) SetHasStatus(val int32) {
	s.HasStatus = val
}

// SetHasAuthMethod sets the value of HasAuthMethod.
func (s *StbUserCreateRequestBody) SetHasAuthMethod(val int32) {
	s.HasAuthMethod = val
}

// SetFirstName sets the value of FirstName.
func (s *StbUserCreateRequestBody) SetFirstName(val string) {
	s.FirstName = val
}

// SetMiddleName sets the value of MiddleName.
func (s *StbUserCreateRequestBody) SetMiddleName(val string) {
	s.MiddleName = val
}

// SetLastName sets the value of LastName.
func (s *StbUserCreateRequestBody) SetLastName(val string) {
	s.LastName = val
}

// SetInitials sets the value of Initials.
func (s *StbUserCreateRequestBody) SetInitials(val string) {
	s.Initials = val
}

// Ref: #/StbUserResponse
type StbUserResponse struct {
	StbUserUuid   OptUUID   `json:"stbUserUuid"`
	StbCustomerId OptInt32  `json:"stbCustomerId"`
	HasStatus     OptInt32  `json:"hasStatus"`
	HasAuthMethod OptInt32  `json:"hasAuthMethod"`
	FirstName     OptString `json:"firstName"`
	MiddleName    OptString `json:"middleName"`
	LastName      OptString `json:"lastName"`
	Initials      OptString `json:"initials"`
}

// GetStbUserUuid returns the value of StbUserUuid.
func (s *StbUserResponse) GetStbUserUuid() OptUUID {
	return s.StbUserUuid
}

// GetStbCustomerId returns the value of StbCustomerId.
func (s *StbUserResponse) GetStbCustomerId() OptInt32 {
	return s.StbCustomerId
}

// GetHasStatus returns the value of HasStatus.
func (s *StbUserResponse) GetHasStatus() OptInt32 {
	return s.HasStatus
}

// GetHasAuthMethod returns the value of HasAuthMethod.
func (s *StbUserResponse) GetHasAuthMethod() OptInt32 {
	return s.HasAuthMethod
}

// GetFirstName returns the value of FirstName.
func (s *StbUserResponse) GetFirstName() OptString {
	return s.FirstName
}

// GetMiddleName returns the value of MiddleName.
func (s *StbUserResponse) GetMiddleName() OptString {
	return s.MiddleName
}

// GetLastName returns the value of LastName.
func (s *StbUserResponse) GetLastName() OptString {
	return s.LastName
}

// GetInitials returns the value of Initials.
func (s *StbUserResponse) GetInitials() OptString {
	return s.Initials
}

// SetStbUserUuid sets the value of StbUserUuid.
func (s *StbUserResponse) SetStbUserUuid(val OptUUID) {
	s.StbUserUuid = val
}

// SetStbCustomerId sets the value of StbCustomerId.
func (s *StbUserResponse) SetStbCustomerId(val OptInt32) {
	s.StbCustomerId = val
}

// SetHasStatus sets the value of HasStatus.
func (s *StbUserResponse) SetHasStatus(val OptInt32) {
	s.HasStatus = val
}

// SetHasAuthMethod sets the value of HasAuthMethod.
func (s *StbUserResponse) SetHasAuthMethod(val OptInt32) {
	s.HasAuthMethod = val
}

// SetFirstName sets the value of FirstName.
func (s *StbUserResponse) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetMiddleName sets the value of MiddleName.
func (s *StbUserResponse) SetMiddleName(val OptString) {
	s.MiddleName = val
}

// SetLastName sets the value of LastName.
func (s *StbUserResponse) SetLastName(val OptString) {
	s.LastName = val
}

// SetInitials sets the value of Initials.
func (s *StbUserResponse) SetInitials(val OptString) {
	s.Initials = val
}

func (*StbUserResponse) createStbUserRes() {}

// Ref: #/StbUserUpdateRequestBody
type StbUserUpdateRequestBody struct {
	StbCustomerId OptInt32  `json:"stbCustomerId"`
	HasStatus     OptInt32  `json:"hasStatus"`
	HasAuthMethod OptInt32  `json:"hasAuthMethod"`
	FirstName     OptString `json:"firstName"`
	MiddleName    OptString `json:"middleName"`
	LastName      OptString `json:"lastName"`
	Initials      OptString `json:"initials"`
}

// GetStbCustomerId returns the value of StbCustomerId.
func (s *StbUserUpdateRequestBody) GetStbCustomerId() OptInt32 {
	return s.StbCustomerId
}

// GetHasStatus returns the value of HasStatus.
func (s *StbUserUpdateRequestBody) GetHasStatus() OptInt32 {
	return s.HasStatus
}

// GetHasAuthMethod returns the value of HasAuthMethod.
func (s *StbUserUpdateRequestBody) GetHasAuthMethod() OptInt32 {
	return s.HasAuthMethod
}

// GetFirstName returns the value of FirstName.
func (s *StbUserUpdateRequestBody) GetFirstName() OptString {
	return s.FirstName
}

// GetMiddleName returns the value of MiddleName.
func (s *StbUserUpdateRequestBody) GetMiddleName() OptString {
	return s.MiddleName
}

// GetLastName returns the value of LastName.
func (s *StbUserUpdateRequestBody) GetLastName() OptString {
	return s.LastName
}

// GetInitials returns the value of Initials.
func (s *StbUserUpdateRequestBody) GetInitials() OptString {
	return s.Initials
}

// SetStbCustomerId sets the value of StbCustomerId.
func (s *StbUserUpdateRequestBody) SetStbCustomerId(val OptInt32) {
	s.StbCustomerId = val
}

// SetHasStatus sets the value of HasStatus.
func (s *StbUserUpdateRequestBody) SetHasStatus(val OptInt32) {
	s.HasStatus = val
}

// SetHasAuthMethod sets the value of HasAuthMethod.
func (s *StbUserUpdateRequestBody) SetHasAuthMethod(val OptInt32) {
	s.HasAuthMethod = val
}

// SetFirstName sets the value of FirstName.
func (s *StbUserUpdateRequestBody) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetMiddleName sets the value of MiddleName.
func (s *StbUserUpdateRequestBody) SetMiddleName(val OptString) {
	s.MiddleName = val
}

// SetLastName sets the value of LastName.
func (s *StbUserUpdateRequestBody) SetLastName(val OptString) {
	s.LastName = val
}

// SetInitials sets the value of Initials.
func (s *StbUserUpdateRequestBody) SetInitials(val OptString) {
	s.Initials = val
}

// A time entry.
// Ref: #/TimeEntry
type TimeEntry struct {
	TimeEntryUuid uuid.UUID `json:"timeEntryUuid"`
	DtLogged      time.Time `json:"dtLogged"`
	WorkedByName  string    `json:"workedByName"`
	ClientName    string    `json:"clientName"`
	MatterName    string    `json:"matterName"`
	HoursLogged   float64   `json:"hoursLogged"`
	DtStart       time.Time `json:"dtStart"`
	DtStop        time.Time `json:"dtStop"`
	Rate          float32   `json:"rate"`
	Amount        float32   `json:"amount"`
	IsBillable    bool      `json:"isBillable"`
	Description   OptString `json:"description"`
	Notes         OptString `json:"notes"`
}

// GetTimeEntryUuid returns the value of TimeEntryUuid.
func (s *TimeEntry) GetTimeEntryUuid() uuid.UUID {
	return s.TimeEntryUuid
}

// GetDtLogged returns the value of DtLogged.
func (s *TimeEntry) GetDtLogged() time.Time {
	return s.DtLogged
}

// GetWorkedByName returns the value of WorkedByName.
func (s *TimeEntry) GetWorkedByName() string {
	return s.WorkedByName
}

// GetClientName returns the value of ClientName.
func (s *TimeEntry) GetClientName() string {
	return s.ClientName
}

// GetMatterName returns the value of MatterName.
func (s *TimeEntry) GetMatterName() string {
	return s.MatterName
}

// GetHoursLogged returns the value of HoursLogged.
func (s *TimeEntry) GetHoursLogged() float64 {
	return s.HoursLogged
}

// GetDtStart returns the value of DtStart.
func (s *TimeEntry) GetDtStart() time.Time {
	return s.DtStart
}

// GetDtStop returns the value of DtStop.
func (s *TimeEntry) GetDtStop() time.Time {
	return s.DtStop
}

// GetRate returns the value of Rate.
func (s *TimeEntry) GetRate() float32 {
	return s.Rate
}

// GetAmount returns the value of Amount.
func (s *TimeEntry) GetAmount() float32 {
	return s.Amount
}

// GetIsBillable returns the value of IsBillable.
func (s *TimeEntry) GetIsBillable() bool {
	return s.IsBillable
}

// GetDescription returns the value of Description.
func (s *TimeEntry) GetDescription() OptString {
	return s.Description
}

// GetNotes returns the value of Notes.
func (s *TimeEntry) GetNotes() OptString {
	return s.Notes
}

// SetTimeEntryUuid sets the value of TimeEntryUuid.
func (s *TimeEntry) SetTimeEntryUuid(val uuid.UUID) {
	s.TimeEntryUuid = val
}

// SetDtLogged sets the value of DtLogged.
func (s *TimeEntry) SetDtLogged(val time.Time) {
	s.DtLogged = val
}

// SetWorkedByName sets the value of WorkedByName.
func (s *TimeEntry) SetWorkedByName(val string) {
	s.WorkedByName = val
}

// SetClientName sets the value of ClientName.
func (s *TimeEntry) SetClientName(val string) {
	s.ClientName = val
}

// SetMatterName sets the value of MatterName.
func (s *TimeEntry) SetMatterName(val string) {
	s.MatterName = val
}

// SetHoursLogged sets the value of HoursLogged.
func (s *TimeEntry) SetHoursLogged(val float64) {
	s.HoursLogged = val
}

// SetDtStart sets the value of DtStart.
func (s *TimeEntry) SetDtStart(val time.Time) {
	s.DtStart = val
}

// SetDtStop sets the value of DtStop.
func (s *TimeEntry) SetDtStop(val time.Time) {
	s.DtStop = val
}

// SetRate sets the value of Rate.
func (s *TimeEntry) SetRate(val float32) {
	s.Rate = val
}

// SetAmount sets the value of Amount.
func (s *TimeEntry) SetAmount(val float32) {
	s.Amount = val
}

// SetIsBillable sets the value of IsBillable.
func (s *TimeEntry) SetIsBillable(val bool) {
	s.IsBillable = val
}

// SetDescription sets the value of Description.
func (s *TimeEntry) SetDescription(val OptString) {
	s.Description = val
}

// SetNotes sets the value of Notes.
func (s *TimeEntry) SetNotes(val OptString) {
	s.Notes = val
}

func (*TimeEntry) createTimeEntryRes() {}

type UpdateStbUserByUUIDBadRequest ErrorMessage

func (*UpdateStbUserByUUIDBadRequest) updateStbUserByUUIDRes() {}

type UpdateStbUserByUUIDInternalServerError ErrorMessage

func (*UpdateStbUserByUUIDInternalServerError) updateStbUserByUUIDRes() {}

type UpdateStbUserByUUIDNotFound ErrorMessage

func (*UpdateStbUserByUUIDNotFound) updateStbUserByUUIDRes() {}

type UpdateStbUserByUUIDUnauthorized ErrorMessage

func (*UpdateStbUserByUUIDUnauthorized) updateStbUserByUUIDRes() {}

type UpdateTimeEntryBadRequest ErrorMessage

func (*UpdateTimeEntryBadRequest) updateTimeEntryRes() {}

type UpdateTimeEntryInternalServerError ErrorMessage

func (*UpdateTimeEntryInternalServerError) updateTimeEntryRes() {}

// UpdateTimeEntryNoContent is response for UpdateTimeEntry operation.
type UpdateTimeEntryNoContent struct{}

func (*UpdateTimeEntryNoContent) updateTimeEntryRes() {}

// The payload for updating a time entry.
// Ref: #/UpdateTimeEntryRequestBody
type UpdateTimeEntryRequestBody struct {
	TestField OptString `json:"testField"`
}

// GetTestField returns the value of TestField.
func (s *UpdateTimeEntryRequestBody) GetTestField() OptString {
	return s.TestField
}

// SetTestField sets the value of TestField.
func (s *UpdateTimeEntryRequestBody) SetTestField(val OptString) {
	s.TestField = val
}

type UpdateTimeEntryUnauthorized ErrorMessage

func (*UpdateTimeEntryUnauthorized) updateTimeEntryRes() {}
