// Code generated by ogen, DO NOT EDIT.

package server

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteStbUserByUUIDParams is parameters of deleteStbUserByUUID operation.
type DeleteStbUserByUUIDParams struct {
	// The UUID of the stb_user to be deleted.
	StbUserUUID uuid.UUID
}

func unpackDeleteStbUserByUUIDParams(packed middleware.Parameters) (params DeleteStbUserByUUIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "stb_user_uuid",
			In:   "path",
		}
		params.StbUserUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteStbUserByUUIDParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteStbUserByUUIDParams, _ error) {
	// Decode path: stb_user_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "stb_user_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.StbUserUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "stb_user_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetStbUserByUUIDParams is parameters of getStbUserByUUID operation.
type GetStbUserByUUIDParams struct {
	// The UUID of the stb_user.
	StbUserUUID uuid.UUID
}

func unpackGetStbUserByUUIDParams(packed middleware.Parameters) (params GetStbUserByUUIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "stb_user_uuid",
			In:   "path",
		}
		params.StbUserUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetStbUserByUUIDParams(args [1]string, argsEscaped bool, r *http.Request) (params GetStbUserByUUIDParams, _ error) {
	// Decode path: stb_user_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "stb_user_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.StbUserUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "stb_user_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RemoveTimeEntryParams is parameters of removeTimeEntry operation.
type RemoveTimeEntryParams struct {
	TimeEntryUuid uuid.UUID
}

func unpackRemoveTimeEntryParams(packed middleware.Parameters) (params RemoveTimeEntryParams) {
	{
		key := middleware.ParameterKey{
			Name: "timeEntryUuid",
			In:   "path",
		}
		params.TimeEntryUuid = packed[key].(uuid.UUID)
	}
	return params
}

func decodeRemoveTimeEntryParams(args [1]string, argsEscaped bool, r *http.Request) (params RemoveTimeEntryParams, _ error) {
	// Decode path: timeEntryUuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "timeEntryUuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TimeEntryUuid = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "timeEntryUuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateStbUserByUUIDParams is parameters of updateStbUserByUUID operation.
type UpdateStbUserByUUIDParams struct {
	// The UUID of the stb_user.
	StbUserUUID uuid.UUID
}

func unpackUpdateStbUserByUUIDParams(packed middleware.Parameters) (params UpdateStbUserByUUIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "stb_user_uuid",
			In:   "path",
		}
		params.StbUserUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateStbUserByUUIDParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateStbUserByUUIDParams, _ error) {
	// Decode path: stb_user_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "stb_user_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.StbUserUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "stb_user_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateTimeEntryParams is parameters of updateTimeEntry operation.
type UpdateTimeEntryParams struct {
	TimeEntryUuid uuid.UUID
}

func unpackUpdateTimeEntryParams(packed middleware.Parameters) (params UpdateTimeEntryParams) {
	{
		key := middleware.ParameterKey{
			Name: "timeEntryUuid",
			In:   "path",
		}
		params.TimeEntryUuid = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateTimeEntryParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateTimeEntryParams, _ error) {
	// Decode path: timeEntryUuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "timeEntryUuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TimeEntryUuid = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "timeEntryUuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
