// Code generated by ogen, DO NOT EDIT.
package server

type CreateStbUserRes interface {
	createStbUserRes()
}

type CreateTimeEntryRes interface {
	createTimeEntryRes()
}

type DeleteStbUserByUUIDRes interface {
	deleteStbUserByUUIDRes()
}

type GetStbUserByUUIDRes interface {
	getStbUserByUUIDRes()
}

type GetStbUsersRes interface {
	getStbUsersRes()
}

type GetTimeEntriesRes interface {
	getTimeEntriesRes()
}

type RemoveTimeEntryRes interface {
	removeTimeEntryRes()
}

type UpdateStbUserByUUIDRes interface {
	updateStbUserByUUIDRes()
}

type UpdateTimeEntryRes interface {
	updateTimeEntryRes()
}
