// Code generated by ogen, DO NOT EDIT.

package server

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateStbUserOperation       OperationName = "CreateStbUser"
	CreateTimeEntryOperation     OperationName = "CreateTimeEntry"
	DeleteStbUserByUUIDOperation OperationName = "DeleteStbUserByUUID"
	GetStbUserByUUIDOperation    OperationName = "GetStbUserByUUID"
	GetStbUsersOperation         OperationName = "GetStbUsers"
	GetTimeEntriesOperation      OperationName = "GetTimeEntries"
	RemoveTimeEntryOperation     OperationName = "RemoveTimeEntry"
	UpdateStbUserByUUIDOperation OperationName = "UpdateStbUserByUUID"
	UpdateTimeEntryOperation     OperationName = "UpdateTimeEntry"
)
