// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: struct_type_read.sql

package strctro

import (
	"context"
)

const getStructTypeByAttPubIdent = `-- name: GetStructTypeByAttPubIdent :one
SELECT 
      struct_type_id
    , att_pub_ident
    , att_value
    , display_order
    , group_name
FROM 
	struct_type
WHERE 
    att_pub_ident = $1
`

type GetStructTypeByAttPubIdentRow struct {
	StructTypeID int16  `json:"structTypeId"`
	AttPubIdent  string `json:"attPubIdent"`
	AttValue     string `json:"attValue"`
	DisplayOrder int16  `json:"displayOrder"`
	GroupName    string `json:"groupName"`
}

func (q *Queries) GetStructTypeByAttPubIdent(ctx context.Context, attPubIdent string) (GetStructTypeByAttPubIdentRow, error) {
	row := q.db.QueryRow(ctx, getStructTypeByAttPubIdent, attPubIdent)
	var i GetStructTypeByAttPubIdentRow
	err := row.Scan(
		&i.StructTypeID,
		&i.AttPubIdent,
		&i.AttValue,
		&i.DisplayOrder,
		&i.GroupName,
	)
	return i, err
}

const getStructTypeByAttValue = `-- name: GetStructTypeByAttValue :one
	SELECT 
      struct_type_id
    , att_pub_ident
    , att_value
    , display_order
    , group_name
FROM 
	struct_type
WHERE 
    att_value = $1
`

type GetStructTypeByAttValueRow struct {
	StructTypeID int16  `json:"structTypeId"`
	AttPubIdent  string `json:"attPubIdent"`
	AttValue     string `json:"attValue"`
	DisplayOrder int16  `json:"displayOrder"`
	GroupName    string `json:"groupName"`
}

func (q *Queries) GetStructTypeByAttValue(ctx context.Context, attValue string) (GetStructTypeByAttValueRow, error) {
	row := q.db.QueryRow(ctx, getStructTypeByAttValue, attValue)
	var i GetStructTypeByAttValueRow
	err := row.Scan(
		&i.StructTypeID,
		&i.AttPubIdent,
		&i.AttValue,
		&i.DisplayOrder,
		&i.GroupName,
	)
	return i, err
}

const getStructTypeByID = `-- name: GetStructTypeByID :one
SELECT 
      struct_type_id
    , att_pub_ident
    , att_value
    , display_order
    , group_name
FROM 
	struct_type
WHERE 
	struct_type_id = $1
`

type GetStructTypeByIDRow struct {
	StructTypeID int16  `json:"structTypeId"`
	AttPubIdent  string `json:"attPubIdent"`
	AttValue     string `json:"attValue"`
	DisplayOrder int16  `json:"displayOrder"`
	GroupName    string `json:"groupName"`
}

func (q *Queries) GetStructTypeByID(ctx context.Context, structTypeID int16) (GetStructTypeByIDRow, error) {
	row := q.db.QueryRow(ctx, getStructTypeByID, structTypeID)
	var i GetStructTypeByIDRow
	err := row.Scan(
		&i.StructTypeID,
		&i.AttPubIdent,
		&i.AttValue,
		&i.DisplayOrder,
		&i.GroupName,
	)
	return i, err
}
